// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9WgygUC9cRCnqOH_E2ktsfC0T_HNkNSs',
    appId: '1:862287662904:web:c73ddbf7fe3dc41da2fbcd',
    messagingSenderId: '862287662904',
    projectId: 'egyzona-7cdca',
    authDomain: 'egyzona-7cdca.firebaseapp.com',
    databaseURL: 'https://egyzona-7cdca-default-rtdb.firebaseio.com',
    storageBucket: 'egyzona-7cdca.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV8hAcNM4wWmvM6x75F77hdhkBon3Z-lA',
    appId: '1:862287662904:android:62608738a7c016a8a2fbcd',
    messagingSenderId: '862287662904',
    projectId: 'egyzona-7cdca',
    databaseURL: 'https://egyzona-7cdca-default-rtdb.firebaseio.com',
    storageBucket: 'egyzona-7cdca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYkSNJon6OJUEJv2HNp-fCc8MMeOFaZPs',
    appId: '1:862287662904:ios:c45ff7b5f1af1e79a2fbcd',
    messagingSenderId: '862287662904',
    projectId: 'egyzona-7cdca',
    databaseURL: 'https://egyzona-7cdca-default-rtdb.firebaseio.com',
    storageBucket: 'egyzona-7cdca.appspot.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYkSNJon6OJUEJv2HNp-fCc8MMeOFaZPs',
    appId: '1:862287662904:ios:97da95a83d99e7ada2fbcd',
    messagingSenderId: '862287662904',
    projectId: 'egyzona-7cdca',
    databaseURL: 'https://egyzona-7cdca-default-rtdb.firebaseio.com',
    storageBucket: 'egyzona-7cdca.appspot.com',
    iosBundleId: 'com.example.ecommerce.RunnerTests',
  );
}
